---
- name: Add apt repository key.
  get_url:
    url: "{{ filebeat_gpg_url }}"
    dest: /etc/apt/trusted.gpg.d/filebeat.asc
    mode: '0644'
    force: true

- name: add beats repository
  apt_repository:
    repo: "{{ filebeat_apt_repo }}"
    state: "{{ filebeat_state }}"
    update_cache: yes

- name: install filebeat
  apt:
    name: filebeat={{ filebeat_version }}
    state: "{{ filebeat_state }}"
    cache_valid_time: "{{ filebeat_cache_valid_time }}"
  notify:
    - restart filebeat
