---
- name: stop filebeat
  service:
    name: filebeat
    state: stopped
    enabled: false
  when: filebeat_state == 'absent'

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup.yml
  when: filebeat_state == 'present'
